CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=201
CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=202
CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=203
CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=204
CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=205
CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=206
CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=207
CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=209
CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=210
CUDA_VISIBLE_DEVICES=1 python PCsampling_demo.py --datanum=211
